TicketsApplicationSystem/Models/ErrorViewModel.cs
using System;

namespace TicketsApplicationSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TicketsApplicationSystem/Models/Executor.cs
using System.Collections.Generic;

namespace TicketsApplicationSystem.Models
{
    public class Executor
    {
        public Executor(string name, string position)
        {
            Name = name;
            Position = position;
        }
        public Executor() { }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        ICollection<Ticket> Tickets { get; set; }

    }
}

TicketsApplicationSystem/Models/State.cs
using System.Collections.Generic;

namespace TicketsApplicationSystem.Models
{
    public class State
    {
        public State(string stateName)
        {
            StateName = stateName;
        }
        public State() { }

        public int Id { get; set; }
        public string StateName { get; set; }
        public ICollection<Ticket> Tickets { get; set; }
        
    }
}

TicketsApplicationSystem/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TicketsApplicationSystem.Models
{
    public class Ticket
    {
        [Key]
        public Guid Id { get; set; }
        
        public int TicketNumber { get; set; }
        [MaxLength(200)]
        public string Title { get; set; }
        [MaxLength(1000)]
        public string Description { get; set; }

        public DateTime DateCreation {get;set;}
        public DateTime? DateChanged { get; set; }
       
        public int StateId { get; set; }
        public State State { get; set; }
        
        public int ExecutorId { get; set; }
        public Executor Executor { get; set; }
        public ICollection<TicketHistory> History { get; set; }

        public Ticket(Guid guid, string title, string description, DateTime dateCreation, int stateId, int execId)
        {
            Id = guid;
            Title = title;
            Description = description;
            DateCreation = dateCreation;
            DateChanged = dateCreation;
            StateId = stateId;
            ExecutorId = execId;
        }
        public Ticket() { }
    }
}

TicketsApplicationSystem/Models/TicketHistory.cs
using System;

namespace TicketsApplicationSystem.Models
{
    public class TicketHistory
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public string State { get; set; }
        public string Comment { get; set; }
        public DateTime? DateChanged { get; set; }

    }
}

TicketsApplicationSystem/ViewModels/TicketViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TicketsApplicationSystem.ViewModels
{
    public class TicketViewModel
    {
        [Display(Name = "Номер заявки")]
        public int TicketNumber { get; set; }
        [Display(Name="Название")]
        public string Title { get; set; }
        [Display(Name="Описание")]
        public string Description { get; set; }
        [Display(Name="Дата создания")]
        public DateTime DateCreation {get;set;}
        [Display(Name="Статус")]
        public int StateId { get; set; } = 1;
        [Display(Name="Исполнитель")]
        public int ExecutorId { get; set; } = 1;
        [Display(Name="Комментарий")]
        public string Comment { get; set; }
        public DateTime? DateChanged { get; set; }
    }
}

TicketsApplicationSystem/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TicketsApplicationSystem.ModelBuilders;
using TicketsApplicationSystem.Models;
using TicketsApplicationSystem.Repository;
using TicketsApplicationSystem.ViewModels;

namespace TicketsApplicationSystem.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ITicketsRepository _ticketsRepository;
        private readonly ITicketsModelBuilder _modelBuilder;

        public TicketsController(TicketsDbContext context, ITicketsRepository ticketsRepository, ITicketsModelBuilder modelBuilder)
        {
            _ticketsRepository = ticketsRepository;
            _modelBuilder = modelBuilder;
        }

        public async Task<IActionResult> Index()
        {
            var ticketsDbContext = _ticketsRepository.GetAllTickets();
            return View(await ticketsDbContext.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ticket = await _ticketsRepository.GetTicketDeailsAsync(id);
            if (ticket == null)
            {
                return NotFound();
            }
            return View(ticket);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TicketNumber,Title,Description,DateCreation,DateChanged,StateId,ExecutorId")] Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                await Task.Run(() => _ticketsRepository.CreateTicket(ticket));
                return RedirectToAction(nameof(Index));
            }
            return View(ticket);
        }



        public async Task<IActionResult> Edit(int id)
        {
            var ticket = await Task.Run(() => _modelBuilder.GetTicketById(id));
            if (ticket == null)
            {
                return NotFound();
            }
            if (_ticketsRepository.States != null)
                ViewData["StateName"] = _ticketsRepository.States;
            if (_ticketsRepository.Executors != null)
                ViewData["ExecutorName"] = _ticketsRepository.Executors;
            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TicketViewModel ticket)
        {
            if (id != ticket.TicketNumber)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await Task.Run(()=>_ticketsRepository.Update(ticket, id));
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ExecutorName"] = _ticketsRepository.Executors;
            return View(ticket);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var ticket = await Task.Run(() => _ticketsRepository.RemoveTicket(id));
            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await Task.Run(() => _ticketsRepository.RemoveTicket(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

TicketsApplicationSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Система ведения заявок</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Tickets" asp-action="Index">TicketsApplicationSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

TicketsApplicationSystem/Views/Tickets/Create.cshtml
@model TicketsApplicationSystem.Models.Ticket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreation" class="control-label"></label>
                <input asp-for="DateCreation" class="form-control" />
                <span asp-validation-for="DateCreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicketsApplicationSystem/Views/Tickets/Delete.cshtml
@model TicketsApplicationSystem.Models.Ticket

@{
    ViewData["Title"] = "Удалить";
}

<h1>Удаление</h1>

<h3>Вы уверены что хотите удалить данную заявку</h3>
<div>
    <h4>Заявка</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateChanged)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateChanged)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StateId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StateId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Executor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Executor.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TicketNumber" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться назад</a>
    </form>
</div>

TicketsApplicationSystem/Views/Tickets/Details.cshtml
@model TicketsApplicationSystem.Models.Ticket

@{
    ViewData["Title"] = "Информация";
}

<h1>Информация</h1>

<div>
    <h4>Заявка</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">Идентификатор заявки</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Id)</dd>
        <dt class = "col-sm-2">Название</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Title)</dd>
        <dt class = "col-sm-2">Описание</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Description)</dd>
        <dt class = "col-sm-2">Дата создания</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.DateCreation)</dd>
        <dt class = "col-sm-2">Дата последнего изменения</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.DateChanged)</dd>
        <dt class = "col-sm-2">Статус</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.State.StateName)</dd>
        <dt class = "col-sm-2">Исполнитель</dt>
        <dd class = "col-sm-10">@Html.DisplayFor(model => model.Executor.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="History" asp-route-id="@Model.TicketNumber">Просмотреть историю</a>
    <a asp-action="Edit" asp-route-id="@Model.TicketNumber">Изменить</a> |
    <a asp-action="Index">Вернуться назад</a>
</div>

TicketsApplicationSystem/Views/Tickets/Edit.cshtml
@model TicketsApplicationSystem.ViewModels.TicketViewModel

@{
    ViewData["Title"] = "Изменить";
}

<h1>Изменить</h1>

<h4>Заявка</h4>
<hr />

<div class="row">
    <div class="col-md-7">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="TicketNumber" class="control-label">Номер заявки</label>
            <input asp-for="TicketNumber" class="form-control" disabled="disabled" />
            <input asp-for="TicketNumber" hidden />
            <div class="form-group">
                <label asp-for="Title" class="control-label">Название</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Описание</label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreation" class="control-label">Дата создания</label>
                <input asp-for="DateCreation" class="form-control" disabled="disabled" />
                <span asp-validation-for="DateCreation" class="text-danger"></span>
                <input asp-for="DateCreation" hidden />
            </div>
            <div class="form-group" id="stateInput">
                <label asp-for="StateId" class="control-label">Статус</label>
                <select asp-for="StateId" class="form-control" onchange="show_comment()" asp-items="ViewBag.StateName"></select>
                <span asp-validation-for="StateId" class="text-danger"></span>
            </div>
            <div class="form-group" id="comment" style="display:none">
                <label asp-for="Comment" class="control-label">Комментарий</label>
                <textarea asp-for="Comment" class="form-control"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExecutorId" class="control-label">Исполнитель</label>
                <select asp-for="ExecutorId" class="form-control" asp-items="ViewBag.ExecutorName"></select>
                <span asp-validation-for="ExecutorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Вернуться назад</a>
</div>
<script type="text/javascript">
    function show_comment() {
        document.getElementById("comment").style.display = "block";
    }
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TicketsApplicationSystem/Views/Tickets/Index.cshtml
@model IEnumerable<TicketsApplicationSystem.Models.Ticket>

@{
    ViewData["Title"] = "Index";
}

<h1>Начальная страница</h1>

<p>
    <a asp-action="Create">Добавить заявку</a>
</p>
<table class="table table-responsive">
    <thead>
        <tr class="align-content-center">
            <th>Номер заявки</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Дата создания</th>
            <th>Дата изменения</th>
            <th>Статус</th>
            <th>Исполнитель</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="text-center">@item.TicketNumber</td>
            <td>@item.Title</td>
            <td>@item.Description</td>
            <td>@item.DateCreation</td>
            <td>@item.DateChanged</td>
            <td>@item.State.StateName</td>
            <td>@item.Executor.Name</td>
            <td class="align-content-center">
                <a asp-action="Edit" asp-route-id="@item.TicketNumber">Изменить</a> |
                <a asp-action="Details" asp-route-id="@item.TicketNumber">Информация</a> |
                <a asp-action="Delete" asp-route-id="@item.TicketNumber">Удалить</a>
            </td>
        </tr>
}
    </tbody>
</table>